theme = "solarized-dark"

#[[theme.overrides]]
#idle_bg = "#fdf7e3"
#idle_fg = "#657b83"
[[icons]]
name = "awesome"

[[block]]
block = "music"
player = "mpd"
buttons = ["prev","play","next"]
max_width = 100
marquee = true

[[block]]
block = "sound"
interval = 1
step_width = 5

[[block]]
block = "net"
device = "wlp3s0"
interval = 3
graph = true

[[block]]
block = "cpu"
interval = 1
#info = 5
#warning = 70
#critical = 90

[[block]]
block = "temperature"
interval = 5
collapsed = true

#[[block]]
#block = "battery"
#interval = 10

[[block]]
block = "time"
# hour:min:sec day:month
format = "%k:%M:%S %e/%m"

