---
- name: set up bash
  file:
    force: true
    state: link
    src: "{{dotdir}}/bashrc"
    dest: ~/.bashrc

- name: set up readline
  file:
    force: true
    state: link
    src: "{{dotdir}}/inputrc"
    dest: ~/.inputrc

- name: set up zsh
  file:
    force: true
    state: link
    src: "{{dotdir}}/zsh"
    dest: ~/.zsh

- name: set up zshrc
  # TODO: template
  file:
    force: true
    state: link
    src: "{{dotdir}}/zshrc"
    dest: ~/.zshrc

- name: set up zprofile
  file:
    force: true
    state: link
    src: "{{dotdir}}/zprofile"
    dest: ~/.zprofile

- name: set up zathura
  file:
    force: true
    state: link
    src: "{{dotdir}}/zathura"
    dest: "{{xdg.config_home}}/zathura"

- name: set up font config
  file:
    force: true
    state: link
    src: "{{dotdir}}/fontconfig"
    dest: "{{xdg.config_home}}/fontconfig"

- name: set up fonts
  file:
    force: true
    state: link
    src: "{{dotdir}}/fonts"
    dest: "{{xdg.data_home}}/fonts"
