#!/bin/sh
# adds headers to Epitech C files with proper date and repo name
# probably author too

AUTHOR='jori.bashllari@epitech.eu'
SRCDIR="$HOME/epitheq/"
YEAR=$(date +"%Y")
PROJNAME=$(git remote -v | head -1 | cut -d'/' -f3 | cut -d' ' -f1)

cat << EOF
/*
** EPITECH PROJECT, $YEAR
** $PROJNAME
** File description:
** something small
*/
EOF
