#!/usr/bin/env bash

# https://github.com/onespaceman/menu-calc
# Calculator for use with rofi/dmenu(2)
# Copying to the clipboard requires xclip

usage() {
    cat << EOF
    $(tput bold)menu-calc$(tput sgr0)
    A calculator for Rofi/dmenu(2)

    $(tput bold)Usage:$(tput sgr0)
        = 4+2
        = (4+2)/(4+3)
        = 4^2
        = sqrt(4)
        = c(2)

    $(tput bold)Force Rofi/dmenu(2):$(tput sgr0)
    By default, if rofi exists, it will be used. To force menu-calc to
    use one or the other, use the --dmenu argument

        = --dmenu=<dmenu_executable>

    $(tput bold)Passing arguments to Rofi/dmenu(2):$(tput sgr0)
    Any parameters after ' -- ' will be passed to Rofi/dmenu(2).

        = -- <Rofi/dmenu(2) args>

    The answer can be copied to the clipboard and used for further calculations
    inside (or outside) Rofi/dmenu.

    If launched outside of Rofi/dmenu the expression may need quotation marks.
EOF
    exit
}

# Process CLI parameters
for var in "$@"
do
    case $var in
        -h|--help) usage ;;
        -d=*|--dmenu=*)
            menu=$(echo $var | cut -d'=' -f 2);
            ;;
    esac
done

# Grab the answer
answer=$(echo "$1" | bc -l | sed '/\./ s/\.\{0,1\}0\{1,\}$//')

# Path to menu application
if [ ! -n "${menu+1}" ]; then
    if [[ -n $(command -v rofi) ]]; then
        menu="$(command -v rofi)"
    elif [[ -n $(command -v dmenu) ]]; then
        menu=$(command -v dmenu)
    else
        echo >&2 "Rofi or dmenu not found"
        exit
    fi
fi

# If using rofi, add the necessary parameters
if [[ $menu == "rofi" || $menu == $(command -v rofi) ]]; then
    menu="$menu -dmenu -lines 3"
elif [[ $menu == "dmenu" || $menu == $(command -v dmenu) ]]; then
    menu="$menu ""$DMENU_OPTIONS"
fi

# Determine args to pass to dmenu/rofi
while [[ $# -gt 0 && $1 != "--" ]]; do
    shift
done
[[ $1 == "--" ]] && shift

action=$(echo -e "Copy to clipboard\nClear\nClose" | $menu "$@" -p "= $answer")

case $action in
    "Clear") $0 "--dmenu=$menu" "--" "$@" ;;
    "Copy to clipboard") echo -n "$answer" | xclip -selection clipboard ;;
    "Close") ;;
    "") ;;
    *) $0 "$answer $action" "--dmenu=$menu" "--" "$@" ;;
esac
