- name: install base packages
  apt: state=latest name="{{item}}"
  with_items:
    - ag
    - alsaUtils
    - apulse
    - ansible
    - calcurse
    - chromium
    - clamav
    - clang
    - ctags
    - dia
    - dunst
    - elinks
    - exfat
    - firefox
    - feh
    - git
    - gnuplot
    - gparted
    - handbrake
    - hashcat
    - htop
    - icdiff
    - imagemagick
    - imv
    - kbfs
    - keybase
    - lftp
    - ldm
    - lxc
    - libnotify
    - mosh
    - msmtp
    - gnome3.nautilus
    - networkmanager
    - neomutt
    - ntfs3g
    - offlineimap
    - pamixer
    - pandoc
    - parallel
    - pass
    - pinentry_ncurses
    - python36Packages.python
    - python36Packages.ipython
    - ranger
    - rsync
    - ruby
    - slurm
    - stdman
    - tlp
    - tmux
    - tree
    - urlview
    - usbutils
    - virtmanager
    - virt-viewer
    - vimHugeX
    - ansible-lint
    - vim-vint
    - shfmt
    - w3m
    - wget
    - xarchiver
    - xorg.xev
    - xdotool
    - xclip
    - xsel
    - zeal
    - (python36.withPackages(pks:
    - pip
    - conda
    - virtualenv
    - yapf
    - neovim
    - terminal_velocity
    - 
    - alacritty
    - arc-theme
    - asciinema
    - beets
    - bsdgames
    - bspwm
    - compton
    - gimp
    - gucharmap
    - handbrake
    - inkscape
    - libreoffice-fresh
    - maim
    - mpd
    - mpv
    - neofetch
    - newsboat
    - ncmpcpp
    - numix-gtk-theme
    - papirus-icon-theme
    - pavucontrol
    - pipes
    - polybar
    - pulsemixer
    - pywal
    - redshift
    - rofi
    - rtv
    - scrot
    - slop
    - sxhkd
    - superTuxKart
    - teeworlds
    - termite
    - tig
    - toilet
    - transmission-gtk
    - #torbrowser
    - unzip
    - vagrant
    - wikicurses
    - wordgrinder
    - youtube-dl
    - zathura
