#! /bin/sh

bspc monitor -d 1 2 3 4 9 10

source ~/.cache/wal/colors.sh
bspc config border_width  0
bspc config window_gap    0

# bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config normal_border_color "$color7"
bspc config focused_border_color "$color5"

sxhkd &
/usr/lib/polkit-1-dde/dde-polkit-agent &
compton &
$HOME/.dots/polybar/launch.sh bspbar &
wal -t -i "$HOME/.dots/img/deltawing_ships.png" &
redshift &
dunst &
