---
- name: get systemd directory
  file:
    state: directory
    dest: "{{xdg.config_home}}/systemd/user"

- name: set up services
  file:
    force: true
    state: link
    src: "{{dotdir}}/systemd"
    dest: "{{xdg.config_home}}/systemd/user"

- name: set up user-dirs.dirs
  file:
    force: true
    state: link
    src: "{{dotdir}}/user-dirs.dirs"
    dest: "{{xdg.config_home}}/user-dirs.dirs"

- name: reload systemd
  systemd:
    daemon_reload: true
    force: true
    scope: global

#  - name: ensure gpg-agent is running
#    systemd:
#      state: started
#      enabled: true
#      name: gpg-agent
#      scope: user

- name: ensure ntp is running
  systemd:
    daemon_reload: true
    state: started
    enabled: true
    name: ntpd

- name: ensure pulse is up
  systemd:
    state: started
    enabled: true
    name: pulseaudio
    scope: user

- name: ensure mpd is up
  systemd:
    enabled: true
    name: mpd
    scope: user

- name: ensure dunst is up
  systemd:
    state: started
    enabled: true
    name: dunst
    scope: user

- name: ensure offlineimap is up
  systemd:
    state: started
    enabled: true
    name: offlineimap
    scope: user
