---
- name: set up elinks files
  file:
    force: true
    state: link
    src: "{{dotdir}}/elinks"
    dest: "{{xdg.config_home}}/elinks/elinks.conf"

- name: set up newsboat
  file:
    force: true
    state: link
    src: "{{dotdir}}/newsboat"
    dest: "{{xdg.config_home}}/newsboat"

- name: set up qutebrowser
  file:
    force: true
    state: link
    src: "{{dotdir}}/qutebrowser"
    dest: "{{xdg.config_home}}/qutebrowser"
