#!/bin/sh

# Load colours
if tput setaf 1 &> /dev/null; then
	tput sgr0; # Reset colours
	bold=$(tput bold);
	reset=$(tput sgr0);
	black=$(tput setaf 16); #000000
	white=$(tput setaf 188); #d7d7d7
	red=$(tput setaf red); #d70000
	green=$(tput setaf green); #00d787
	yellow=$(tput setaf yellow); #ffaf00
	blue=$(tput setaf blue); #0097d7
	magenta=$(tput setaf magenta); #d75faf
	cyan=$(tput setaf cyan); #8787af
	teal=$(tput setaf teal); #008787
else
	bold='';
	reset="\e[0m";
	black="\e[1;38;5;16m";
	white="\e[1;38;5;188m";
	red="\e[1;38;5;160m";
	green="\e[1;38;5;42m";
	yellow="\e[1;38;5;214m";
	blue="\e[1;38;5;32m";
	magenta="\e[1;38;5;169m";
	cyan="\e[1;38;5;103m";
	teal="\e[1;38;5;30m";
fi;

# Generate uptime and
seconds="$(< /proc/uptime)"
seconds="${seconds/.*}"
days="$((seconds / 60 / 60 / 24)) days"
hours="$((seconds / 60 / 60 % 24)) hours"
mins="$((seconds / 60 % 60)) minutes"
# Format the days, hours and minutes.
strip_date() {
	case "$1" in
		"0 "*) unset "${1/* }" ;;
		"1 "*) printf "%s" "${1/s}" ;;
		*)     printf "%s" "$1" ;;
	esac
}
days="$(strip_date "$days")"
hours="$(strip_date "$hours")"
mins="$(strip_date "$mins")"
uptime="${days:+$days, }${hours:+$hours, }${mins}"
uptime="${uptime%', '}"
uptime="${uptime:-${seconds} seconds}"

# Get weather if the wttr file has been downloaded more than 1 hour ago or doesn't exist
LOCATION="Tirana"
if [ -f ~/.cache/wttr ]; then
	file_time=$(stat --format='+%Y' "/home/alter2000/.cache/wttr")
	current_time=$(date +%s)
	if (( file_time < ( current_time - ( 60 * 60 * 1 ) ) )); then
	wget -q -O ~/.cache/wttr wttr.in/$LOCATION?qn1
fi
else
	wget -q -O ~/.cache/wttr wttr.in/$LOCATION?qn1
	touch ~/wttr_warning_$(date +%Y-%m-%d-%H-%M)
fi

# Print results
echo -e "${blue}${bold}--------------------- H E L L O  T H E R E ---------------------${reset}"
echo ""
echo -e "${blue}Host:${reset} \t\t\t ${bold}$(whoami)@$(uname -n)${reset}"
echo -e "${blue}Shell:${reset} \t\t\t $SHELL"
echo -e "${blue}Uptime:${reset} \t\t $uptime"
echo "${reset}"
echo ""
df -H --total -t ext4 -t fuse.sshfs -t fat32 -t ntfs -t btrfs -t xfs
echo "${reset}"
echo ""
echo -e "                      $(head -n -2 ~/.cache/wttr)"
echo ""
echo "${magenta}$(calcurse --appointment --todo --quiet)${reset}"
echo ""
echo -e "           ==== $(date -R) ===="
echo "${reset}"

# Delete used variables
unset {file_time,current_time}
unset {seconds,mins,hours,days,uptime}
unset {bold,reset,black,white,red,green,yellow,blue,magenta,cyan,teal}
