---
- name: set up alacritty
  file:
    force: true
    state: link
    src: "{{dotdir}}/alacritty"
    dest: "{{xdg.config_home}}/alacritty"

- name: set up termite
  file:
    force: true
    state: link
    src: "{{dotdir}}/termite"
    dest: "{{xdg.config_home}}/termite"

- name: set up gitconfig
  # TODO: template
  file:
    force: true
    state: link
    src: "{{dotdir}}/gitconfig"
    dest: "~/.gitconfig"

- name: set up mailcap
  file:
    force: true
    state: link
    src: "{{dotdir}}/mailcap"
    dest: "~/.mailcap"

- name: set up ranger
  file:
    force: true
    state: link
    src: "{{dotdir}}/ranger"
    dest: "{{xdg.config_home}}/ranger"

- name: set up rtv
  file:
    force: true
    state: link
    src: "{{dotdir}}/rtv"
    dest: "{{xdg.config_home}}/rtv"

- name: set up tmux
  file:
    force: true
    state: link
    src: "{{dotdir}}/tmux_skel"
    dest: "~/.tmux.conf"

- name: set up vim
  file:
    force: true
    state: link
    src: "{{dotdir}}/vim"
    dest: "{{vim.dir}}"
  shell: "vim +PlugInstall +qall"
