#!/bin/python

import urllib.request, json

city = "Tirana"
api_key = "b029a961e78ea317dd9877ee437dbbc1"

weather = eval(str(urllib.request.urlopen("http://api.openweathermap.org/data/2.5/weather?q={}&APPID={}".format(city, api_key)).read())[2:-1])

info = weather["weather"][0]["description"].capitalize()
temp = int(float(weather["main"]["temp"]) - 272.15)

print("%s, %i °" % (info, temp))
