# fuck the law with the dick in my hand
alias ytmp3="youtube-dl --extract-audio --audio-format mp3"
alias webget="wget -mpP"
alias wq="echo \"this isn't vim, autismo\""
alias q="wq"
alias e="$EDITOR"

alias ipy="ipython"
alias tree="tree -C"
alias view="vimpager"
alias wag="python ./manage.py"
# alias kid="cheat ""| less"
alias conc="source /opt/context-minimals/setuptex && context "
alias pandoc="pandoc --reference-links --reference-location=block --atx-headers --slide-level=2 --email-obfuscation=references"

alias ls="ls --color=auto --group-directories-first"
alias l="ls -AlhF"
alias ll="ls -Alh"
alias la="ls -Ah"

alias gst="git status -sb"
alias gaa="git add -A"
alias gc="git commit"
alias gp="git push"
alias gh="git hub"
alias gb="git bb"

alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"

alias suffer="pacaur -Syu"
alias pain="pacaur -S"
alias painl="pacaur -U"
alias paind="pacaur -S --asdeps"
alias pare="pacaur -R"
alias parm="pacaur -Rsn"
alias parmorphans="sudo pacman -Rns $(pacman -Qtdq)"
alias parmnew="sudo find / -name '*.pacnew' 2>/dev/null"
