autoload -Uz promptinit && promptinit
PURE_CMD_MAX_EXEC_TIME=180
PURE_PROMPT_SYMBOL=δ
PURE_PROMPT_VICMD_SYMBOL=μ
PURE_PROMPT_SYMBOL_COLOR=green
#PURE_GIT_DOWN_ARROW=
#PURE_GIT_UP_ARROW=
prompt pure

### POWERLEVEL9K ###
#DEFAULT_USER="alter2000"
#POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( background_jobs dir vcs custom_wifi_signal )
#POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=( vi_mode status time )
#POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=""
#POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR="%F{$(( $DEFAULT_BACKGROUND - 2 ))}|%f"
#POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=""
#POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR="%F{$(( $DEFAULT_BACKGROUND - 2 ))}|%f"
#POWERLEVEL9K_BATTERY_LOW_THRESHOLD=30
#POWERLEVEL9K_BATTERY_VERBOSE=false
#POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
#POWERLEVEL9K_SHORTEN_DELIMITER=''
#POWERLEVEL9K_DIR_SHOW_WRITABLE=true
#POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
#POWERLEVEL9K_STATUS_HIDE_SIGNAME=true
#POWERLEVEL9K_CUSTOM_WIFI_SIGNAL="p9k_wifi_signal"
#POWERLEVEL9K_VI_INSERT_MODE_STRING="i"
#POWERLEVEL9K_VI_COMMAND_MODE_STRING="n"
