---
- name: set up beets
  file:
    force: true
    state: link
    src: "{{dotdir}}/beets"
    dest: "{{xdg.config_home}}/beets"

- name: set up mpd
  file:
    force: true
    state: link
    src: "{{dotdir}}/mpd"
    dest: "{{xdg.config_home}}/mpd"

- name: set up ncmpcpp
  file:
    force: true
    state: link
    src: "{{dotdir}}/ncmpcpp"
    dest: ~/.ncmpcpp

# - name: set up transmission
#   file:
#     force: true
#     state: link
#     src: "{{dotdir}}/transmission/settings.json"
#     dest: "{{xdg.config_home}}/transmission/settings.json"
